packages:
  - .

minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  supabase: true
  esbuild: true
  sharp: true
  unrs-resolver: true
packageImportMethod: clone-or-copy
