'use client';
import {createPortal} from 'react-dom';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {ArrowRight,Check,ChevronDown,Download,FlaskConical,Pause,Play,RefreshCw,Square} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {LabConfig,labConfigSchema} from '@/lib/lab-contract';
import {actionBlock,LabSubmission} from '@/lib/lab-run-client';
import './lab.css';
import LabReplay from './lab-replay';
const pc=(n:number)=>(100*n).toFixed(1)+'%',num=(n:number)=>n.toLocaleString();
const active=(s:string)=>['queued','running','pausing','cancelling'].includes(s);
function download(name:string,value:any){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function requestAPI(path:string,options?:RequestInit){const r=await fetch('/api/lab/'+path,options);const d:any=await r.json();if(!r.ok)throw Error(d.error||'The lab could not complete this request.');return d;}
export type LabHandle={execute:(name:string,config:LabConfig,stage:number)=>Promise<string>};
type Props={evidenceHost:HTMLDivElement|null;onVisual:(data:any)=>void;onInspect:()=>void;computeId:string|null;onBusy:(busy:boolean)=>void;onHealth:(health:any)=>void;config:LabConfig;onConfig:(c:LabConfig)=>void;ready:boolean;browsing:boolean;locked:boolean;selectedId:string|null;onSelect:(id:string|null)=>void;onContext:(job:any,evidence:any)=>void;onMessage:(text:string)=>void;onDiscuss:()=>void};
export default forwardRef<LabHandle,Props>(function LabPanel({evidenceHost,onVisual,onInspect,computeId,onBusy,onHealth,config,onConfig,ready,browsing,locked,selectedId,onSelect,onContext,onMessage,onDiscuss},ref){
 const [health,setHealth]=useState<any>(null),[jobs,setJobs]=useState<any[]>([]),[job,setJob]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[example,setExample]=useState(false),[seed,setSeed]=useState(0),[metric,setMetric]=useState('validationLoss');
 const alive=useRef(true);
 async function api(path:string,options?:RequestInit){const headers=new Headers(options?.headers);if(computeId)headers.set('X-Compute-ID',computeId);return requestAPI(path,{...options,headers});}
 useEffect(()=>{onBusy(busy);},[busy]);
 useEffect(()=>{onHealth(health);},[health]);
 const previousJob=useRef<any>(null);
 const submission=useRef(new LabSubmission()),selected=useRef<string|null>(selectedId),inFlight=useRef(false);
 const patch=(v:Partial<LabConfig>)=>onConfig({...config,...v});
 const setConfig=onConfig;
 async function refresh(){try{const h=await api('health');if(!alive.current)return;setHealth(h);if(h.connected){const d=await api('jobs');if(!alive.current)return;setJobs(d.jobs);if(selected.current==='example')return;if(selected.current){const id=selected.current;const j=await api('jobs/'+id);if(selected.current===id)setJob(j);}}}catch(e:any){setHealth({connected:false,status:'unavailable',message:e.message});}}
 useEffect(()=>{alive.current=true;refresh();const t=setInterval(refresh,5000);return()=>{alive.current=false;clearInterval(t);};},[]);
 useEffect(()=>{if(selectedId!==selected.current){selected.current=selectedId;if(selectedId==='example')measured();else if(selectedId)select(selectedId);else setJob(null);}},[selectedId]);
 useEffect(()=>{const r=job?.result;onVisual(job?{config:job.config,ancestors:r?.models?.[1]?.runs?.[0]?.ancestors,result:r,progress:job.progress}:null);if(r&&!example&&previousJob.current?.id===job.id&&previousJob.current.status!=='completed')onMessage('Comparison complete. The candidate changed held-out accuracy by '+(r.delta*100).toFixed(1)+' percentage points. Open the measured evidence below to inspect uncertainty, timing and ablation before deciding what to try next.');previousJob.current=job;onContext(job?{id:job.id,status:job.status,config:job.config,progress:job.progress?{phase:job.progress.phase,completedUpdates:job.progress.completedUpdates,totalUpdates:job.progress.totalUpdates}:null,source:example?'development-example':'personal-trainer'}:null,r?{delta:r.delta,speedup:r.speedup,interval:r.interval,originalAccuracy:r.models[0].accuracy,candidateAccuracy:r.models[1].accuracy,ablationAccuracy:r.models[1].runs.reduce((s:number,x:any)=>s+x.ablationAccuracy,0)/r.models[1].runs.length}:null);},[job,example]);
 async function select(id:string){setError('');setExample(false);setSeed(0);selected.current=id;onSelect(id);try{const j=await api('jobs/'+id);if(selected.current===id)setJob(j);}catch(e:any){setError(e.message);}}
 async function execute(name:string,draft=config,stage=ready?4:0):Promise<string>{
  if(inFlight.current)return 'A run request is already in progress.';
  if(name==='status'){await refresh();return 'The experiment card shows the latest status received from your trainer. If the trainer is unreachable, its last known state is preserved.';}
  if(name==='repeat'){if(!job?.config)return 'Select a saved experiment to reuse its exact specification.';onConfig(job.config);return 'The selected run’s exact specification is now the draft. Its seeds and data settings are preserved. Review it here before starting a separate run.';}
  const blocked=actionBlock(name,!!health?.connected,stage,job,example);if(blocked)return blocked;
  inFlight.current=true;setBusy(true);setError('');
  try{
   let j:any;
   if(name==='start'){
    const c=labConfigSchema.safeParse(draft);if(!c.success)throw Error('Check the settings: sample counts must be even and all values must stay within the supported limits.');
    j=await submission.current.start(c.data,api);setExample(false);selected.current=j.id;onSelect(j.id);setSeed(0);
   }else j=await api('jobs/'+job.id+'/'+name,{method:'POST'});
   setJob(j);return name==='start'?'Your trainer accepted the exact specification. The run is '+j.status+'. Progress and measured results will appear here.':'Your trainer acknowledged the request. Run status: '+j.status+'.';
  }catch(e:any){setError(e.message);return 'The trainer request could not be confirmed: '+e.message+' Your draft is preserved. Retry safely to check the same submission.';}finally{inFlight.current=false;setBusy(false);}
 }
 useImperativeHandle(ref,()=>({execute}));
 async function start(){onMessage(await execute('start'));}
 async function action(name:string){onMessage(await execute(name));}
 async function measured(){try{const r=await fetch('/research/lab-example.json');if(!r.ok)throw Error('The measured example could not load.');const result:any=await r.json();selected.current='example';onSelect('example');setJob({id:'measured-example',status:'completed',config:result.config,result});setExample(true);setSeed(0);}catch(e:any){setError(e.message);}}
 const result=job?.result,progress=job?.progress;
 const curves=result?result.models[0].runs[seed].history.map((h:any,i:number)=>({step:h.step,original:h[metric],candidate:result.models[1].runs[seed].history[i]?.[metric]})):progress?.history?.map((h:any)=>({step:h.step,[progress.model===0?'original':'candidate']:h[metric]}))||[];
 const percent=progress?Math.round(100*progress.completedUpdates/progress.totalUpdates):0;
 const workspace=<section className="fl-workspace fl-lab fl-evidence-surface">{error&&job&&<div className="fl-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss run error">×</button></div>}
   {job&&<div className="fl-run-head"><h2>{job?example?'Measured development run':job.status==='completed'?'Comparison complete':'Experiment progress':'Your experiments'}</h2>{job&&<span className={'fl-state '+job.status}>{job.status}</span>}</div>}
   {job&&<details className="fl-details"><summary>This run’s fixed specification <ChevronDown size={15}/></summary><p>Editing the draft changes the next run only.</p><pre className="fl-json">{JSON.stringify(job.config,null,2)}</pre></details>}
   {job&&!result&&<div className="fl-progress"><p>{job.status==='queued'?'Waiting for the training machine.':job.status==='paused'?'Paused at a saved checkpoint. Resume continues from that update.':job.status==='failed'?job.error:job.status==='cancelled'?'Cancelled. No completed result is claimed.':progress?.phase==='evaluating'?'Training complete. Measuring held-out decisions and inference speed.':progress?`${progress.model===0?'Original':'Candidate'} · seed ${progress.seed} · update ${progress.step||0} of ${job.config.updates}`:'Preparing verified source connectivity…'}</p><progress max={100} value={percent} aria-label="Training updates completed"/><span>{percent}% of training updates saved</span><div className="fl-actions">{['queued','running'].includes(job.status)&&<button className="da-text-button" disabled={busy} onClick={()=>action('pause')}><Pause size={16}/>Pause</button>}{['paused','failed'].includes(job.status)&&<button className="da-primary" disabled={busy} onClick={()=>action('resume')}><Play size={16}/>Resume checkpoint</button>}{(active(job.status)||job.status==='paused')&&<button className="da-text-button" disabled={busy} onClick={()=>action('cancel')}><Square size={15}/>Cancel run</button>}</div></div>}
   {result&&<><p className="fl-result-context">{example?'Measured on the development CPU; this is not a run on your connected trainer. ':''}{result.config.task==='cue-memory'?'Cue memory':'Noisy evidence'} · {result.config.seeds.length} paired seeds · {result.config.updates} updates · {result.config.duplicates} inherited copies</p><div className="fl-outcome"><div><span>Accuracy difference</span><h3>{result.delta>0?'+':''}{(result.delta*100).toFixed(1)} <small>pp</small></h3><p>{!result.interval?'One seed cannot establish a reliable gain.':result.interval[0]>0?'An exploratory gain on this benchmark.':result.interval[1]<0?'The candidate underperformed on this benchmark.':'A reliable improvement is not established.'}</p></div><div className="fl-scores">{result.models.map((m:any,i:number)=><div key={m.name}><span style={{color:i?'#9ac6ff':'#a2adbe'}}>{m.name}</span><b>{pc(m.accuracy)}</b><small>{m.latencyMs.toFixed(1)} ms / decision</small></div>)}</div></div>
   <div className="fl-evidence-stats"><div><span>Paired 95% interval</span><b>{result.interval?result.interval.map((x:number)=>(x*100).toFixed(1)).join(' to ')+' pp':'Not estimated'}</b></div><div><span>Candidate speed</span><b>{result.speedup.toFixed(2)}× original</b></div><div><span>Validation selected</span><b>{result.selectedByValidation?'Candidate':'Original'}</b></div></div><p className="fl-caption">Intervals across a few seeds are exploratory. Timing uses seven warmed executions per seed, on the same CPU, excluding rendering.</p></>}
   <details hidden={!result&&!curves.length} className="fl-details fl-evidence-details" open={result?undefined:true}><summary>Learning curves, held-out tests & reproducibility <ChevronDown size={15}/></summary>{(curves.length>0)&&<div className="fl-curves"><div className="fl-chart-tools"><h3>Learning, as measured</h3><label>Curve<select aria-label="Learning curve metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="validationLoss">Validation loss</option><option value="trainLoss">Training batch loss</option><option value="validationAccuracy">Validation accuracy</option></select></label>{result&&<label>Seed<select aria-label="Experiment seed" value={seed} onChange={e=>setSeed(Number(e.target.value))}>{result.config.seeds.map((s:number,i:number)=><option key={s} value={i}>{s}</option>)}</select></label>}</div><div className="fl-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={curves} margin={{top:15,right:15,left:0,bottom:8}}><CartesianGrid vertical={false} stroke="#25303b"/><XAxis dataKey="step" stroke="#8a99a8"/><YAxis width={60} tick={{fontSize:12}} tickFormatter={v=>metric==='validationAccuracy'?pc(v):Number(v).toFixed(3)} stroke="#8a99a8" domain={metric==='validationAccuracy'?[0,1]:['auto','auto']}/><Tooltip contentStyle={{background:'#16202a',border:'1px solid #344250',borderRadius:12,color:'#f4f7fa'}}/><Line dataKey="original" name="Original" stroke="#a2adbe" dot={false} strokeWidth={2} isAnimationActive={false}/><Line dataKey="candidate" name="Candidate" stroke="#9ac6ff" dot={false} strokeWidth={2} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="fl-caption">Gray: original · Blue: candidate · Horizontal axis: training update</p></div>}
   {result&&<><LabReplay result={result} seed={seed}/><div className="fl-checks"><h3>Did internal processing change?</h3><div className="fl-table-wrap"><table><thead><tr><th>Seed {result.config.seeds[seed]}</th><th>Original</th><th>Candidate</th></tr></thead><tbody>{[['Before training',(r:any)=>pc(r.initialAccuracy)],['After training',(r:any)=>pc(r.test.accuracy)],['With recurrence removed',(r:any)=>pc(r.ablationAccuracy)],['Recurrent parameter change',(r:any)=>r.parameterChangeNorms.edge_scale.toPrecision(4)],['Trainable connections',(r:any)=>num(r.recurrentParameters)],['Selected update',(r:any)=>r.bestStep]].map(([label,format]:any)=><tr key={label}><td>{label}</td>{result.models.map((m:any)=><td key={m.name}>{format(m.runs[seed])}</td>)}</tr>)}</tbody></table></div><p className="fl-caption">Parameter change is an L2 norm from initialization. If accuracy survives removing recurrence, this task has not established a benefit from the fly’s wiring.</p></div>
   <div className="fl-trials"><h3>Every held-out decision</h3><p className="fl-caption">Filled: correct · Outlined: incorrect. Both rows use the same inputs.</p>{result.models.map((m:any,i:number)=><div key={m.name}><span>{m.name}</span><div>{m.runs[seed].test.predictions.map((p:number,j:number)=><span className={p===m.runs[seed].test.targets[j]?'correct':''} style={{'--trial-color':i?'#9ac6ff':'#a2adbe'} as React.CSSProperties} key={j} title={`Trial ${j+1}: predicted ${p}, target ${m.runs[seed].test.targets[j]}`} aria-label={`Trial ${j+1}: predicted ${p}, target ${m.runs[seed].test.targets[j]}`}/>)}</div></div>)}</div>
   <details className="fl-details"><summary>Reproduce & inspect source ancestry <ChevronDown size={15}/></summary><p>{result.protocol}</p><p>Graph: <code>{result.graph.sha256}</code></p><p>Code: <code>{result.codeSha256}</code></p><p>Dataset: <code>{result.datasetSha256}</code></p><p>Copied source body IDs: {result.models[1].runs[0].ancestors.join(', ')||'No copies'}</p><p>Download the configuration, actual datasets, and model checkpoints. The trainer package includes a replay verifier. Matching code, graph and pinned environment are required for deterministic reproduction.</p>{job.artifacts&&<button className="da-text-button" onClick={()=>download('artifacts.json',job.artifacts)}><Download size={14}/>Artifact checksums</button>}{job.artifacts?.map((a:any)=><a key={a.name} href={'/api/lab/jobs/'+job.id+'/artifacts/'+a.name+(computeId?'?compute='+encodeURIComponent(computeId):'')} className="fl-artifact"><Download size={14}/>{a.name}<small>{(a.bytes/1048576).toFixed(1)} MB</small></a>)}{example&&<p>The bundled report includes measured predictions and source hashes. Full checkpoint downloads are available for experiments on your connected trainer.</p>}</details>
   <div className="fl-actions"><button className="da-text-button" onClick={()=>download('measured-lab-result.json',result)}><Download size={16}/>Measured report</button><button className="da-text-button" onClick={()=>{setConfig(result.config);onMessage('The selected result’s exact settings are now the draft. Changes apply to the next run only.');}}>Reuse exact specification</button></div></>}
   </details>
   {result&&<button className="da-text-button" onClick={onDiscuss}>Discuss this result <ArrowRight size={16}/></button>}
  </section>;
 return <section className="fl-lab fl-inline" aria-label="Experiment workspace">
  {error&&!job&&<div className="fl-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss lab error">×</button></div>}
  <div className="fl-layout">{browsing&&<div className="de-runs-heading"><span className="da-kicker">EXPERIMENT HISTORY</span><h2>Your past runs</h2><p>{jobs.length?"Choose a run to inspect its progress and measured evidence.":health?.connected?"Your completed and ongoing comparisons will appear here.":"Choose your machine from Compute to load its saved runs."}</p></div>}{ready&&<section className="fl-setup">
   <span className="da-kicker">YOUR EXPERIMENT · LIVE DRAFT</span><h2>{config.task==='cue-memory'?'Remember through a delay':'Find a signal in noise'}</h2>
   <p className="fl-draft-summary">{config.duplicates} copies · seeds {config.seeds.join(", ")} · {config.updates} updates · {config.trainExamples} / {config.validationExamples} / {config.testExamples} train / validation / test</p><p>Train the original fly topology and a candidate with inherited neuron copies. Both receive identical examples and training budgets.</p>
   <details className="fl-details fl-settings"><summary>Inspect or edit all settings <ChevronDown size={15}/></summary><fieldset disabled={locked||busy}><label>Task<select value={config.task} onChange={e=>patch({task:e.target.value as LabConfig['task']})}><option value="cue-memory">Remember a cue</option><option value="noisy-evidence">Decide under noise</option></select></label>
   <div className="fl-architecture"><div><span>Original</span><b>165,122</b><small>source neurons</small></div><ArrowRight size={20}/><div><span>Candidate</span><b>{num(165122+config.duplicates)}</b><small>{config.duplicates} inherited copies</small></div></div>
   <div className="fl-fields"><label>Added neurons<input aria-label="Added neurons" type="number" min={0} max={128} value={config.duplicates} onChange={e=>patch({duplicates:Number(e.target.value)})}/></label><label>Source population<select value={config.population} onChange={e=>patch({population:e.target.value as LabConfig['population']})}><option value="cb_intrinsic">Central brain</option><option value="descending_neuron">Descending neurons</option><option value="visual_projection">Visual projection</option></select></label></div>
   <div className="fl-fields"><label>Training updates<input type="number" min={1} max={200} value={config.updates} onChange={e=>patch({updates:Number(e.target.value)})}/></label><label>Paired seeds<select value={config.seeds.length} onChange={e=>patch({seeds:Array.from({length:Number(e.target.value)},(_,i)=>((config.seeds[0]||41)+i)%10000)})}><option value={1}>1 · check</option><option value={2}>2 · check</option><option value={3}>3 · pilot</option><option value={4}>4 · pilot</option><option value={5}>5 · pilot</option></select></label></div>
   <details className="fl-details"><summary>Data & learning settings <ChevronDown size={15}/></summary><div className="fl-fields">{([['trainExamples','Training examples',512],['validationExamples','Validation examples',256],['testExamples','Test examples',512],['timesteps','Sequence steps',16],['batch','Batch size',8]] as const).map(([key,label,max])=><label key={key}>{label}<input type="number" min={key==='batch'?1:key==='timesteps'?4:8} max={max} step={key.includes('Examples')?2:1} value={config[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}<label>Learning rate<input type="number" min={.00001} max={.05} step={.001} value={config.learningRate} onChange={e=>patch({learningRate:Number(e.target.value)})}/></label><label>First seed<input type="number" min={0} max={9999} value={config.seeds[0]} onChange={e=>patch({seeds:config.seeds.map((_,i)=>(Number(e.target.value)+i)%10000)})}/></label></div></details>
   </fieldset></details><div className="fl-protocol"><Check size={16}/><p>All retained connection strengths train, together with neuron-class dynamics and the decision readout. Validation selects checkpoints. Test results are measured afterwards.</p></div>
   <p className="fl-caption">{config.trainExamples} / {config.validationExamples} / {config.testExamples} examples per seed. This is a small synthetic benchmark. A larger network may be slower or less accurate.</p>
   {!health?.connected&&<p className="fl-caption">To run this plan, choose a machine from Compute in the chat box.</p>}<div className="fl-actions"><button className="da-text-button" onClick={onInspect}><FlaskConical size={16}/>Inspect change</button><button className="da-text-button" onClick={()=>download('experiment-config.json',config)}><Download size={16}/>Specification</button><button className="da-primary" disabled={!health?.connected||busy||locked||!!(job&&['queued','running','pausing','paused','cancelling'].includes(job.status))} onClick={start}><Play size={15}/>{busy?'Submitting…':'Start comparison'}</button></div>
  </section>}
   {!job&&browsing&&<div className="fl-empty"><button className="da-text-button" onClick={measured}>Inspect a measured full-graph example <ArrowRight size={15}/></button></div>}
   {browsing&&jobs.length>0&&<details className="fl-history fl-details" open><summary>Saved runs · {jobs.length} <ChevronDown size={15}/></summary>{jobs.map(j=><button key={j.id} aria-pressed={job?.id===j.id} onClick={()=>select(j.id)}><span>{j.config.task==='cue-memory'?'Cue memory':'Noisy evidence'}<small>{new Date(j.created*1000).toLocaleString()} · {j.config.duplicates} copies</small></span><span>{j.status}<ArrowRight size={14}/></span></button>)}</details>}
  {evidenceHost&&createPortal(workspace,evidenceHost)}</div>
 </section>;
});
