import type {Plan} from './experiment-planner';
export function labOptions(stage:number){return stage===0?['Remember a cue','Decide under noise']:stage===1?['Higher accuracy','Faster decisions','Balance both']:stage===2?['Add 32 inherited copies','Keep the original topology']:stage===3?['Quick check · 1 seed','Pilot · 3 seeds','Pilot · 5 seeds']:['Review the specification','Use 64 copies'];}
export function labRespond(text:string,stage:number,plan:Plan){
 const t=text.toLowerCase(),p={...plan};
 const answer=(text:string,next=stage)=>({text,stage:next,plan:p});
 if(/prun|slow.*decay|physics|doom|mario|minecraft|xor|two.cue/.test(t))return answer('This persistent milestone supports cue memory or noisy evidence, with up to 128 inherited neuron copies and trainable internal connections. That requested feature is not implemented here. Which supported comparison would you like?');
 if(stage===0){if(!/cue|remember|memor|beacon|nois|evidence/.test(t))return answer('Should the network remember a cue through a delay, or infer a direction from noisy observations?');p.task=/nois|evidence/.test(t)?'evidence':'beacon';p.prune=0;p.memory=false;p.duplicates=32;p.population='cb_intrinsic';p.epochs=12;p.seed=41;return answer('We can compare both networks on identical held-out trials. What matters most: accuracy, decision speed, or both?',1);}
 if(stage===1){if(!/accur|fast|speed|both|balanc/.test(t))return answer('Choose accuracy, speed, or a balance of both.');p.goal=/both|balanc/.test(t)?'balance':/fast|speed/.test(t)?'speed':'accuracy';return answer('The first structural intervention is 32 copies of central-brain neurons, inheriting their measured connections. Extra capacity may help, but adds computation and can hurt performance. Both networks will train their internal connection strengths. Would you like those copies, or an identical-topology control?',2);}
 if(stage===2||stage===4){const match=t.match(/(\d+)\s*(?:inherited |neuron )?copies/);if(!/add|cop|keep|original|review/.test(t))return answer('Choose 0–128 inherited copies. The original graph remains the comparison baseline.');const count=match?Number(match[1]):/keep|original/.test(t)?0:p.duplicates;if(count>128)return answer('This pilot supports at most 128 copies. Choose a smaller count.');p.duplicates=count;p.prune=0;p.memory=false;return stage===4?answer('The specification is updated. Review the exact settings below before starting.'):answer('We will use '+count+' inherited copies and preserve measured edges. How many paired seeds: one for an execution check, three for an exploratory pilot, or five?',3);}
 if(stage===3){if(!/1|one|quick|3|three|5|five|pilot/.test(t))return answer('Choose one, three, or five paired seeds.');p.seeds=/5|five/.test(t)?5:/1|one|quick/.test(t)?1:3;p.budget='quick';p.epochs=12;return answer('The pilot specification is ready: '+p.seeds+' paired seeds, 12 updates, and 32 / 16 / 32 training, validation and test examples per seed. Validation selects checkpoints before test evaluation. Review and start here; a persistent training machine must be connected.',4);}
 return answer('Review the specification below.');
}
