const env=process.env;
import {labDb} from './lab-db';
import {sealCredential,unsealCredential} from './credential-crypto';
import {Provider,ProviderStatus,listProviderModels,providerName} from './model-providers';
export const providerEnvironment=()=>env as unknown as {OPENAI_API_KEY?:string;ANTHROPIC_API_KEY?:string;PROVIDER_ENCRYPTION_KEY?:string};
const idFor=(userId:string,p:Provider)=>JSON.stringify([userId,p]);
export async function providerCredential(userId:string,provider:Provider){const e=providerEnvironment();const row:any=await labDb().prepare('SELECT sealed_key,key_hint FROM provider_connections WHERE id = ? AND user_id = ?').bind(idFor(userId,provider),userId).first();if(row)return{key:await unsealCredential(row.sealed_key,e.PROVIDER_ENCRYPTION_KEY||'',idFor(userId,provider)),hint:row.key_hint,source:'personal' as const};const key=provider==='openai'?e.OPENAI_API_KEY:e.ANTHROPIC_API_KEY;return key?{key,hint:'Site connection',source:'site' as const}:null;}
export async function saveProviderCredential(userId:string,provider:Provider,key:string){const id=idFor(userId,provider),sealed=await sealCredential(key,providerEnvironment().PROVIDER_ENCRYPTION_KEY||'',id);await labDb().prepare('INSERT INTO provider_connections (id,user_id,provider,sealed_key,key_hint,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sealed_key=excluded.sealed_key,key_hint=excluded.key_hint,updated_at=excluded.updated_at').bind(id,userId,provider,sealed,'•••• '+key.slice(-4),new Date().toISOString()).run();}
export async function removeProviderCredential(userId:string,provider:Provider){await labDb().prepare('DELETE FROM provider_connections WHERE id = ? AND user_id = ?').bind(idFor(userId,provider),userId).run();}
export async function providerStatus(userId:string,provider:Provider):Promise<ProviderStatus>{try{const credential=await providerCredential(userId,provider);if(!credential)return{id:provider,name:providerName(provider),status:'missing',models:[]};const models=await listProviderModels(provider,credential.key);return{id:provider,name:providerName(provider),status:'connected',models,hint:credential.hint,source:credential.source};}catch(e:any){return{id:provider,name:providerName(provider),status:'error',models:[],message:e.name==='TimeoutError'?'Connection check timed out. Retry.':e.status?e.message:'The connection could not be loaded. Retry.'};}}
