# Sourced by dev.sh after the shared banner; needs no Node, uv or Docker.
lab_section 'START HERE'
lab_command 'make run' 'Set up dependencies + Docker + services; launch the lab'
lab_command 'make help' 'Show this reference (also the default for make)'
lab_section 'WORKSPACE'
lab_command 'make setup' 'Install locked pnpm and uv/Python dependencies'
lab_command 'make start' 'Start or reuse services; alias: make start-all'
lab_command 'make stop' 'Stop the lab; retain data and checkpoints'
lab_command 'make status' 'Show service health, URLs and log location'
lab_command 'make check-ports' 'Inspect preferred ports without changing services'
lab_command 'make logs' 'Follow the website log; Ctrl-C exits the viewer'
lab_section 'VERIFY'
lab_command 'make check' 'All linters, tests, agent checks and production build'
lab_command 'make test' 'All suites, with an aggregated result summary'
lab_command 'make test-web' 'Node persistence and data tests'
lab_command 'make test-research' 'Browser/research and HTTP contract checks'
lab_command 'make live-cost-check' 'One tiny paid model call to prove cost recording (LIVE_COST_CHECK=1)'
lab_command 'make test-python' 'uv-managed numerical tests'
lab_command 'make lint' 'Formatting, types, lint and agent configuration'
lab_command 'make lint-fix' 'Apply supported fixes, then verify'
lab_command 'make build' 'Compile the production website'
lab_command 'make check-agents' 'Validate shared skills and reviewer registrations'
lab_section 'DATA'
lab_command 'make backup' 'Stop website; save private database/artifact backup'
lab_command 'make restore BACKUP=...' 'Restore backups/FOLDER into an empty workspace'
lab_section 'PORTS & LOGS'
printf '    WEB_PORT=3000  TRAINER_PORT=8000\n    SUPABASE_PORT_BASE=54320\n\n    Busy defaults select alternatives. Explicit busy ports fail.\n    Runtime: .local-data/    Secrets: .env.local (preserved)\n\n'
