-- Service-tier rates, provider billing connections, and billed cost reports for reconciliation.
ALTER TABLE lab.model_prices
 ADD COLUMN input_flex_per_mtok numeric CHECK(input_flex_per_mtok >= 0),
 ADD COLUMN output_flex_per_mtok numeric CHECK(output_flex_per_mtok >= 0),
 ADD COLUMN cache_read_flex_per_mtok numeric CHECK(cache_read_flex_per_mtok >= 0),
 ADD COLUMN input_priority_per_mtok numeric CHECK(input_priority_per_mtok >= 0),
 ADD COLUMN output_priority_per_mtok numeric CHECK(output_priority_per_mtok >= 0),
 ADD COLUMN cache_read_priority_per_mtok numeric CHECK(cache_read_priority_per_mtok >= 0),
 ADD COLUMN cache_write_1h_per_mtok numeric CHECK(cache_write_1h_per_mtok >= 0),
 ADD COLUMN fast_multiplier numeric CHECK(fast_multiplier >= 1);
ALTER TABLE lab.llm_usage
 ADD COLUMN service_tier text NOT NULL DEFAULT 'standard' CHECK(service_tier IN ('standard','flex','priority','fast')),
 ADD COLUMN cache_write_1h_tokens integer NOT NULL DEFAULT 0 CHECK(cache_write_1h_tokens >= 0);
-- Admin-scoped keys used only to read organization cost reports; never used for model calls.
CREATE TABLE lab.billing_connections(
 id text PRIMARY KEY,
 user_id text NOT NULL,
 provider text NOT NULL CHECK(provider IN ('openai','anthropic')),
 sealed_key text NOT NULL,
 key_hint text NOT NULL,
 updated_at text NOT NULL
);
CREATE INDEX billing_connections_user ON lab.billing_connections(user_id);
-- Daily billed amounts as reported by the provider for the whole organization.
CREATE TABLE lab.provider_costs(
 provider text NOT NULL CHECK(provider IN ('openai','anthropic')),
 day date NOT NULL,
 model text NOT NULL DEFAULT '',
 line_item text NOT NULL DEFAULT '',
 usd numeric NOT NULL CHECK(usd >= 0),
 fetched_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(provider, day, model, line_item)
);
CREATE TABLE lab.billing_syncs(
 id bigserial PRIMARY KEY,
 provider text NOT NULL CHECK(provider IN ('openai','anthropic')),
 started_at timestamptz NOT NULL DEFAULT now(),
 finished_at timestamptz,
 from_day date NOT NULL,
 to_day date NOT NULL,
 status text NOT NULL CHECK(status IN ('running','succeeded','failed')),
 rows_upserted integer NOT NULL DEFAULT 0,
 error text
);
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=2,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-haiku-4-5-20251001';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=2,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-haiku-4-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=6,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-3-7-sonnet-20250219';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=0.5,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-3-haiku-20240307';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=30,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-3-opus-20240229';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=6,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-sonnet-4-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=6,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-sonnet-4-5-20250929';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=4,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-sonnet-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=6,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-sonnet-4-6';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=30,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-1';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=30,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-1-20250805';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=30,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-20250514';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-5-20251101';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-6';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-6-20260205';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-7';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-opus-4-7-20260416';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=20,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-fable-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=20,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-fable-5-1';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=2 WHERE provider='anthropic' AND model='claude-opus-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=10,fast_multiplier=2 WHERE provider='anthropic' AND model='claude-opus-4-8';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=6,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-sonnet-4-20250514';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=3.5,output_priority_per_mtok=14,cache_read_priority_per_mtok=0.875,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=3.5,output_priority_per_mtok=14,cache_read_priority_per_mtok=0.875,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1-2025-04-14';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.7,output_priority_per_mtok=2.8,cache_read_priority_per_mtok=0.175,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1-mini';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.7,output_priority_per_mtok=2.8,cache_read_priority_per_mtok=0.175,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1-mini-2025-04-14';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.2,output_priority_per_mtok=0.8,cache_read_priority_per_mtok=0.05,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1-nano';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.2,output_priority_per_mtok=0.8,cache_read_priority_per_mtok=0.05,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4.1-nano-2025-04-14';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=4.25,output_priority_per_mtok=17,cache_read_priority_per_mtok=2.125,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=8.75,output_priority_per_mtok=26.25,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o-2024-05-13';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=4.25,output_priority_per_mtok=17,cache_read_priority_per_mtok=2.125,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o-2024-08-06';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=4.25,output_priority_per_mtok=17,cache_read_priority_per_mtok=2.125,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o-2024-11-20';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.25,output_priority_per_mtok=1,cache_read_priority_per_mtok=0.125,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o-mini';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=0.25,output_priority_per_mtok=1,cache_read_priority_per_mtok=0.125,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-4o-mini-2024-07-18';
UPDATE lab.model_prices SET input_flex_per_mtok=0.625,output_flex_per_mtok=5,cache_read_flex_per_mtok=0.0625,input_priority_per_mtok=2.5,output_priority_per_mtok=20,cache_read_priority_per_mtok=0.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5';
UPDATE lab.model_prices SET input_flex_per_mtok=0.625,output_flex_per_mtok=5,cache_read_flex_per_mtok=0.0625,input_priority_per_mtok=2.5,output_priority_per_mtok=20,cache_read_priority_per_mtok=0.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.1';
UPDATE lab.model_prices SET input_flex_per_mtok=0.625,output_flex_per_mtok=5,cache_read_flex_per_mtok=0.0625,input_priority_per_mtok=2.5,output_priority_per_mtok=20,cache_read_priority_per_mtok=0.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.1-2025-11-13';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=2.5,output_priority_per_mtok=20,cache_read_priority_per_mtok=0.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.1-chat-latest';
UPDATE lab.model_prices SET input_flex_per_mtok=0.875,output_flex_per_mtok=7,cache_read_flex_per_mtok=0.0875,input_priority_per_mtok=3.5,output_priority_per_mtok=28,cache_read_priority_per_mtok=0.35,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.2';
UPDATE lab.model_prices SET input_flex_per_mtok=0.875,output_flex_per_mtok=7,cache_read_flex_per_mtok=0.0875,input_priority_per_mtok=3.5,output_priority_per_mtok=28,cache_read_priority_per_mtok=0.35,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.2-2025-12-11';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=3.5,output_priority_per_mtok=28,cache_read_priority_per_mtok=0.35,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.2-chat-latest';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=3.5,output_priority_per_mtok=28,cache_read_priority_per_mtok=0.35,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.3-chat-latest';
UPDATE lab.model_prices SET input_flex_per_mtok=5,output_flex_per_mtok=25,cache_read_flex_per_mtok=0.5,input_priority_per_mtok=20,output_priority_per_mtok=100,cache_read_priority_per_mtok=2,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-6-astra';
UPDATE lab.model_prices SET input_flex_per_mtok=2,output_flex_per_mtok=10,cache_read_flex_per_mtok=0.2,input_priority_per_mtok=8,output_priority_per_mtok=40,cache_read_priority_per_mtok=0.8,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.6';
UPDATE lab.model_prices SET input_flex_per_mtok=2,output_flex_per_mtok=10,cache_read_flex_per_mtok=0.2,input_priority_per_mtok=8,output_priority_per_mtok=40,cache_read_priority_per_mtok=0.8,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.6-sol';
UPDATE lab.model_prices SET input_flex_per_mtok=1,output_flex_per_mtok=6,cache_read_flex_per_mtok=0.1,input_priority_per_mtok=4,output_priority_per_mtok=24,cache_read_priority_per_mtok=0.4,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.6-terra';
UPDATE lab.model_prices SET input_flex_per_mtok=0.1,output_flex_per_mtok=0.6,cache_read_flex_per_mtok=0.01,input_priority_per_mtok=0.4,output_priority_per_mtok=2.4,cache_read_priority_per_mtok=0.04,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.6-luna';
UPDATE lab.model_prices SET input_flex_per_mtok=2.5,output_flex_per_mtok=15,cache_read_flex_per_mtok=0.25,input_priority_per_mtok=12.5,output_priority_per_mtok=75,cache_read_priority_per_mtok=1.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.5';
UPDATE lab.model_prices SET input_flex_per_mtok=2.5,output_flex_per_mtok=15,cache_read_flex_per_mtok=0.25,input_priority_per_mtok=12.5,output_priority_per_mtok=75,cache_read_priority_per_mtok=1.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.5-2026-04-23';
UPDATE lab.model_prices SET input_flex_per_mtok=1.25,output_flex_per_mtok=7.5,cache_read_flex_per_mtok=0.13,input_priority_per_mtok=5,output_priority_per_mtok=30,cache_read_priority_per_mtok=0.5,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4';
UPDATE lab.model_prices SET input_flex_per_mtok=1.25,output_flex_per_mtok=7.5,cache_read_flex_per_mtok=0.13,input_priority_per_mtok=5,output_priority_per_mtok=30,cache_read_priority_per_mtok=0.5,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4-2026-03-05';
UPDATE lab.model_prices SET input_flex_per_mtok=0.375,output_flex_per_mtok=2.25,cache_read_flex_per_mtok=0.0375,input_priority_per_mtok=1.5,output_priority_per_mtok=9,cache_read_priority_per_mtok=0.15,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4-mini';
UPDATE lab.model_prices SET input_flex_per_mtok=0.375,output_flex_per_mtok=2.25,cache_read_flex_per_mtok=0.0375,input_priority_per_mtok=1.5,output_priority_per_mtok=9,cache_read_priority_per_mtok=0.15,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4-mini-2026-03-17';
UPDATE lab.model_prices SET input_flex_per_mtok=0.1,output_flex_per_mtok=0.625,cache_read_flex_per_mtok=0.01,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4-nano';
UPDATE lab.model_prices SET input_flex_per_mtok=0.1,output_flex_per_mtok=0.625,cache_read_flex_per_mtok=0.01,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5.4-nano-2026-03-17';
UPDATE lab.model_prices SET input_flex_per_mtok=0.625,output_flex_per_mtok=5,cache_read_flex_per_mtok=0.0625,input_priority_per_mtok=2.5,output_priority_per_mtok=20,cache_read_priority_per_mtok=0.25,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5-2025-08-07';
UPDATE lab.model_prices SET input_flex_per_mtok=0.125,output_flex_per_mtok=1,cache_read_flex_per_mtok=0.0125,input_priority_per_mtok=0.45,output_priority_per_mtok=3.6,cache_read_priority_per_mtok=0.045,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5-mini';
UPDATE lab.model_prices SET input_flex_per_mtok=0.125,output_flex_per_mtok=1,cache_read_flex_per_mtok=0.0125,input_priority_per_mtok=0.45,output_priority_per_mtok=3.6,cache_read_priority_per_mtok=0.045,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5-mini-2025-08-07';
UPDATE lab.model_prices SET input_flex_per_mtok=0.025,output_flex_per_mtok=0.2,cache_read_flex_per_mtok=0.0025,input_priority_per_mtok=2.5,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5-nano';
UPDATE lab.model_prices SET input_flex_per_mtok=0.025,output_flex_per_mtok=0.2,cache_read_flex_per_mtok=0.0025,input_priority_per_mtok=2.5,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='gpt-5-nano-2025-08-07';
UPDATE lab.model_prices SET input_flex_per_mtok=1,output_flex_per_mtok=4,cache_read_flex_per_mtok=0.25,input_priority_per_mtok=3.5,output_priority_per_mtok=14,cache_read_priority_per_mtok=0.875,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='o3';
UPDATE lab.model_prices SET input_flex_per_mtok=1,output_flex_per_mtok=4,cache_read_flex_per_mtok=0.25,input_priority_per_mtok=3.5,output_priority_per_mtok=14,cache_read_priority_per_mtok=0.875,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='o3-2025-04-16';
UPDATE lab.model_prices SET input_flex_per_mtok=0.55,output_flex_per_mtok=2.2,cache_read_flex_per_mtok=0.138,input_priority_per_mtok=2,output_priority_per_mtok=8,cache_read_priority_per_mtok=0.5,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='o4-mini';
UPDATE lab.model_prices SET input_flex_per_mtok=0.55,output_flex_per_mtok=2.2,cache_read_flex_per_mtok=0.138,input_priority_per_mtok=2,output_priority_per_mtok=8,cache_read_priority_per_mtok=0.5,cache_write_1h_per_mtok=NULL,fast_multiplier=NULL WHERE provider='openai' AND model='o4-mini-2025-04-16';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=20,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-mythos-5';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=20,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-mythos-5-1';
UPDATE lab.model_prices SET input_flex_per_mtok=NULL,output_flex_per_mtok=NULL,cache_read_flex_per_mtok=NULL,input_priority_per_mtok=NULL,output_priority_per_mtok=NULL,cache_read_priority_per_mtok=NULL,cache_write_1h_per_mtok=20,fast_multiplier=NULL WHERE provider='anthropic' AND model='claude-mythos-preview';
REVOKE ALL ON ALL TABLES IN SCHEMA lab FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA lab FROM PUBLIC, anon, authenticated;
